version: '3'
services:
  user-db:
    build: .
    container_name: user-db
    labels:
      - registerDomain
    environment:
      - MYSQL_ROOT_PASSWORD=mysqlpassword
      - MYSQL_PASSWORD=userdbpwd
      - MYSQL_USER=userdb
      - MYSQL_DATABASE=user
      - TZ=America/Sao_Paulo
    image: mysql:8
    command:
      --default-authentication-plugin=mysql_native_password
    ports:
      - "3307:3306"
    volumes:
      - ./init_userdb.sql:/docker-entrypoint-initdb.d/init_userdb.sql
